16/Feb/2023 18:37:17   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/  (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name."), <traceback object at 0x0000027FB9042140>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
16/Feb/2023 18:37:17   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "GET /news/ HTTP/1.1" 500 206013  None
16/Feb/2023 19:58:51   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/  (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 18: 'get_available_languages'. Did you forget to register or load this tag?"), <traceback object at 0x000001731D6D0A80>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_available_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 18: 'get_available_languages'. Did you forget to register or load this tag?
16/Feb/2023 19:58:51   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "GET /news/ HTTP/1.1" 500 200604  None
16/Feb/2023 20:25:38   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/  (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError('Unknown argument for \'trans\' tag: \'Новостей\'. The only options available are \'noop\', \'context\' "xxx", and \'as VAR\'.'), <traceback object at 0x00000201A406A6C0>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\templatetags\cache.py", line 84, in do_cache
    nodelist = parser.parse(("endcache",))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\templatetags\i18n.py", line 443, in do_translate
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Unknown argument for 'trans' tag: 'Новостей'. The only options available are 'noop', 'context' "xxx", and 'as VAR'.
16/Feb/2023 20:25:38   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "GET /news/ HTTP/1.1" 500 219042  None
18/Feb/2023 16:36:12   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/index/  (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('default.html'), <traceback object at 0x000002AB14399FC0>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\NewsPaper\news\views.py", line 128, in get
    return HttpResponse(render(request, 'default.html', context))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: default.html
18/Feb/2023 16:36:12   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "GET /news/index/ HTTP/1.1" 500 115044  None
18/Feb/2023 17:18:38   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/index/  (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('default.html'), <traceback object at 0x0000020041D98880>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\NewsPaper\news\views.py", line 128, in get
    return HttpResponse(render(request, 'default.html', context))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: default.html
18/Feb/2023 17:18:38   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "GET /news/index/ HTTP/1.1" 500 115496  None
18/Feb/2023 17:19:01   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/index/  (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('default.html'), <traceback object at 0x0000020041D9B480>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\NewsPaper\news\views.py", line 128, in get
    return HttpResponse(render(request, 'default.html', context))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: default.html
18/Feb/2023 17:19:01   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "GET /news/index/ HTTP/1.1" 500 115488  None
19/Feb/2023 14:27:15   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/  (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 12: 'get_current_timezone', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x000002787D5114C0>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_timezone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'get_current_timezone', expected 'endblock'. Did you forget to register or load this tag?
19/Feb/2023 14:27:15   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "GET /news/ HTTP/1.1" 500 230343  None
19/Feb/2023 15:23:15   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/index/  (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'news' not found. 'news' is not a valid view function or pattern name."), <traceback object at 0x000002137CA03F80>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\NewsPaper\news\views.py", line 130, in post
    return redirect('news')
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'news' not found. 'news' is not a valid view function or pattern name.
19/Feb/2023 15:23:15   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "POST /news/index/ HTTP/1.1" 500 97968  None
19/Feb/2023 16:13:31   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/  (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Unclosed tag on line 48: 'for'. Looking for one of: empty, endfor."), <traceback object at 0x0000011E3A493680>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 48: 'for'. Looking for one of: empty, endfor.
19/Feb/2023 16:13:31   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "GET /news/ HTTP/1.1" 500 211586  None
19/Feb/2023 16:16:48   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\utils\log.py    Internal Server Error: /news/index/  (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('default.html'), <traceback object at 0x000001C45A72F300>)
Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\denis\PycharmProjects\East\NewsPaper\news\views.py", line 126, in get
    return HttpResponse(render(request, 'default.html', context))
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: default.html
19/Feb/2023 16:16:48   ERROR    C:\Users\denis\PycharmProjects\East\venv\lib\site-packages\django\core\servers\basehttp.py    "GET /news/index/ HTTP/1.1" 500 111172  None
